name: it230-project
recipe: laravel
config:
  webroot: ./public
tooling:
  abracadabra:
    service: appserver
    cmd:
      - composer install
      - cp .env.example .env
      - php artisan key:generate
      - lando php artisan migrate --seed
